# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- name: Initialize /etc/rancher/k3s directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Make images directory
  ansible.builtin.file:
    path: "{{ k3s_server_location }}/agent/images/"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create manifest directory
  ansible.builtin.file:
    path: "{{ k3s_server_location }}/server/manifests"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: Create manifests directory for temp configuration
  ansible.builtin.file:
    path: "/tmp/k3s"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0755'

- name: Set arm k3s architecture
  ansible.builtin.set_fact:
    k3s_architecture: "arm"
  when: ansible_architecture == "arm64" or ansible_architecture == "aarch64"

- name: Set amd64 k3s architecture
  ansible.builtin.set_fact:
    k3s_architecture: "amd64"
  when: ansible_architecture == "x86_64"

- name: Copy k3s images into place
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version | urlencode }}/k3s-airgap-images-{{ k3s_architecture | urlencode }}.tar.gz"
    dest: "{{ k3s_server_location }}/agent/images/"
    owner: root
    group: root
    mode: '0755'

- name: Enable IPv6 router advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: true
  tags: sysctl

- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: 'Defaults    secure_path = {{ secure_path[ansible_distribution_file_variety] }}'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
  when: ansible_distribution_file_variety == "SUSE"
