= Metal Provisioning
:toc:
:toclevels: 3

Ansible for building and configuring non-compute nodes.

== Ansible Config

The `ansible.cfg` file in this repository is copied into an NCN image during build-time.

== Roles and Playbooks

Playbooks live in the root of the repository, those prefixed with `^pb` are used in the packer build pipeline.

* `packer.yml` inventory file for packer builds
* `^pb*` playbooks for packer builds and may not run when invoked on a live system.
* All other playbooks may be invoked on a live system at `/srv/cray/metal-provision/` using either (depending on which is available):

[horizontal]
Legacy Location:: `/etc/ansible/csm_ansible/bin/ansible-playbook`
New location:: `/opt/cray/ansible/bin/ansible-playbook`

=== Best Practices

==== Packages and Services

The `node-images-hypervisor` role should be used as a reference for handling packages and services when creating new node-images roles (e.g. roles for image artifacts).

* Packages should have a set of tasks to install them for common distros.
* Services should have a set of tasks to enable/start/disable/stop them for common distros.

Several roles for CSM 1.5 images and earlier (e.g. `node-images-ncn-common`) have two service handling models, this should not be replicated.
This handling exists as a legacy function:

* `roles/<role>/vars/services/<distro>.yml`
* `roles/<role>/vars/<medium>.yml`
** e.g. `metal.yml` contains metal specific variables, including a `services` dictionary while the file lives outside of the `services/` folder.
** This does not support multiple distros, putting the role in a corner.

==== Medium Specific Tasks and Variables

In order to provide ubiquitous images, the `metal.yml`, `google.yml`, and `vagrant.yml` tasks (and variable) files should be used lightly.
Ideally an image is set up without these.

==== Distro Agnostic

When using any distro specific Ansible module a developer should put it in a conditional block.

Conditional distro blocks should key off of:

* `when: ansible_distribution_file_variety == "Debian"`
* `when: ansible_distribution_file_variety == "RedHat"`
* `when: ansible_distribution_file_variety == "SUSE"`

It is not required to create the other distro blocks, but it is encouraged to install placeholders.

== Packages

Packages are controlled by group variables, typically in a file following the path structure of:

[source,bash]
----
group_vars/<group>/packages.<distro>[.<arch>].yml
----
NOTE: Each `arch` specific file also uses a different parent variable name, e.g. `packages_x86_64` instead of `packages`.

There is also a base collection of packages defined in `/vars`, these are pulled into top-level playpooks such as `pb_node_images.yml`.

=== Adding new Distros

. Add a new YAML file for the distro.
The `&lt;distro&gt;` name needs to match the Ansible fact
`ansible_distribution_file_variety | lower`.
. Update the `group_vars/<group>/packages.<distro>[.<arch>]*.yml` file for the new distro and package manager, copy-paste one of the other distro's `block`s and refactor it for the appropriate package manager module.

Note:: The `&lt;arch&gt;` is optional.
Defining a YAML by `&lt;distro&gt;` without an `&lt;arch&gt;` value implies that the packages listed are intended for all architectures.

=== Adding architecture specific package lists

The package installation tasks already search for architectures depending on the environment, to add a new architecture one can drop a new YAML file for the appropriate `&lt;distro&gt;` (the value returned by
`ansible_distribution_file_variety | lower`) and `-&lt;arch&gt;` (the value returned by `ansible_architecture`).

Note:: There must always be a `&lt;distro&gt;.yml` file before there can be any `&lt;distro&gt;-&lt;arch&gt;.yml` files.
