#
# MIT License
#
# (C) Copyright 2023-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
bashrc_aliases:
  - 'alias ip=''ip -c'''
  - 'alias ll=''ls -l --color'''
  - 'alias lid=''for file in $(ls -1d /sys/bus/pci/drivers/*/0000\\:*/net/*); do printf "%-6s %s\n" "$(basename $file)" $(grep PCI_ID "$(dirname $(dirname $file))/uevent" | cut -f 2 -d "="); done'''
  - 'alias wipeoff=''for script in /var/www/ncn-*/script.ipxe; do sed -i ''s/metal.no-wipe=0/metal.no-wipe=1/g'' \$script; done; wipestat'''
  - 'alias wipeon=''for script in /var/www/ncn-*/script.ipxe; do sed -i ''s/metal.no-wipe=1/metal.no-wipe=0/g'' \$script; done; wipestat'''
  - 'alias wipestat=''grep -o metal.no-wipe=[01] /var/www/ncn-*/script.ipxe'''
  - 'source <(kubectl completion bash) 2>/dev/null'
