---
- name: Register active gitea version
  ansible.builtin.shell: "set -eo pipefail; /usr/local/bin/gitea -v | cut -d' ' -f 3"
  args:
    executable: /bin/bash
  register: gitea_active_version
  changed_when: false
  failed_when: false
  when: gitea_version_check|bool

- name: Download gitea binary
  ansible.builtin.get_url:
    url: "{{ gitea_dl_url }}"
    dest: /usr/local/bin/gitea
    owner: root
    group: root
    mode: '0755'
    force: true
  notify: "Restart gitea"
  when: (not gitea_version_check|bool) or (not ansible_check_mode and (gitea_active_version.stdout != gitea_version))

- name: Create gitea group
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    system: true
    state: "present"

- name: Create gitea user
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    home: "{{ gitea_home }}"
    system: true

- name: Install prerequisites for Gitea
  ansible.builtin.package:
    name: git
    state: present

- name: Create config and data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0755'
  with_items:
    - "{{ gitea_config_dir }}"

- name: Create gitea data directories
  ansible.builtin.file:
    state: directory
    path: "{{ item.path | default(item) }}"
    owner: "{{ item.owner | default(gitea_user) }}"
    group: "{{ item.group | default(gitea_user) }}"
    mode: '0755'
    recurse: true
  with_items:
    - "{{ gitea_home }}"
    - "{{ gitea_home }}/data"
    - "{{ gitea_home }}/custom"
    - "{{ gitea_home }}/custom/https"
    - "{{ gitea_home }}/custom/mailer"
    - "{{ gitea_home }}/indexers"
    - "{{ gitea_home }}/log"
    - "{{ gitea_repository_root }}"

- name: Setup gitea systemd service
  ansible.builtin.template:
    src: gitea.service.j2
    dest: /usr/lib/systemd/system/gitea.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - "Reload systemd"
    - "Restart gitea"

- name: Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Configure gitea
  ansible.builtin.template:
    src: gitea.ini.j2
    dest: "{{ gitea_config_dir }}/gitea.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0600'
  notify: "Restart gitea"

- name: Service gitea
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
