#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
packages:
  - apache2=2.4.51-150400.6.11.1
  - apparmor-profiles=3.0.4-150500.11.6.1
  - conman=0.3.1-150500.1.2
  - dnsmasq=2.86-150400.14.3
  - fawkes-httpboot-grub=1.0-1
  - gnu_parallel=20230122-bp155.1.5
  - gnu_parallel-bash-completion=20230122-bp155.1.5
  - gnu_parallel-zsh-completion=20230122-bp155.1.5
  - gru=0.0.4-1
  - metal-init=1.4.6-1
  - metal-ipxe=2.5.1-1
  - metal-nexus=1.4.0-3.38.0_1
  - metal-observability=1.0.9-1
  - pdsh=2.34-150500.44.1
  - sqlite3=3.39.3-150000.3.20.1
  - terraform=0.13.4-6.3.1
