#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
- include_tasks:
    file: packages.yml
    apply:
      tags: packages
  tags:
    - never
    - packages

- name: Copy motd
  copy:
    src: motd
    dest: /etc/motd

- name: Blacklist kernel modules
  lineinfile:
    create: true
    path: /etc/modprobe.d/disabled-modules.conf
    regexp: 'install {{ item }} /bin/true'
    line: 'install {{ item }} /bin/true'
    state: present
  loop: "{{ kernel.blacklists.standard }}"

- name: Blacklist kernel modules for kdump
  lineinfile:
    backrefs: true
    path: /etc/sysconfig/kdump
    regexp: '^(KDUMP_COMMANDLINE_APPEND)="(.*)"'
    line: "\\g<1>=\"module_blacklist={{ kernel.blacklists.kdump | join(',') }} \\g<2>\""

- name: Create /etc/containers
  file:
    path: /etc/containers
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create storage.conf
  file:
    path: /etc/containers/storage.conf
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Configure podman so it will run with fuse-overlayfs
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^#?mount_program ='
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'

- name: Copy cloud.cfg configuration
  copy:
    src: cloud.cfg
    dest: /etc/cloud/cloud.cfg

- name: Copy logrotate configuration
  synchronize:
    src: logrotate.d/
    dest: /etc/logrotate.d/

- name: Copy systemd configuration
  synchronize:
    delete: no
    src: systemd/
    dest: /usr/lib/systemd/system/

- name: Copy sysctl configuration
  synchronize:
    delete: false
    src: sysctl.d/
    dest: /etc/sysctl.d/

- name: Install scripts and utilities
  synchronize:
    src: "{{ item }}"
    dest: /srv/cray/
  loop:
  - scripts
  - utilities

- name: Install craysys shortcut into /bin
  file:
    src: /srv/cray/utilities/common/craysys/craysys
    dest: /bin/craysys
    state: link

- name: Create cray.sh profile
  file:
    path: /etc/profile.d/cray.sh
    state: touch
    mode: '0644'
    owner: root
    group: root

- name: Export cray path
  lineinfile:
    path: /etc/profile.d/cray.sh
    regexp: '^export PYTHONPATH='
    line: 'export PYTHONPATH="/srv/cray/utilities/common"'

- name: Google tasks
  include_tasks:
    file: google.yml
    apply:
      tags: google
  tags:
    - google
    - never

- name: Metal tasks
  include_tasks:
    file: metal.yml
    apply:
      tags: metal
  tags:
    - metal
    - never

- name: Vagrant tasks
  include_tasks:
    file: vagrant.yml
    apply:
      tags: vagrant
  tags:
    - never
    - vagrant

- include_tasks:
    file: services.yml
