#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
services:
  - enabled: no
    name: cray-heartbeat
  - enabled: no
    name: postfix
  - enabled: no
    name: mdcheck_continue
  - enabled: no
    name: mdcheck_start
  - enabled: no
    name: mdmonitor-oneshot
  - enabled: no
    name: mdmonitor
  - enabled: yes
    name: spire-agent
  - enabled: yes
    name: apache2
  - enabled: yes
    name: basecamp
  - enabled: yes
    name: ca-certificates
  - enabled: yes
    name: chronyd
  - enabled: yes
    name: dnsmasq
  - enabled: yes
    name: getty@tty1
  - enabled: yes
    name: issue-generator
  - enabled: yes
    name: kdump-early
  - enabled: yes
    name: kdump
  - enabled: yes
    name: lldpad
  - enabled: yes
    name: multi-user.target
  - enabled: yes
    name: nexus
  - enabled: yes
    name: purge-kernels
  - enabled: yes
    name: rc-local
  - enabled: yes
    name: rollback
  - enabled: yes
    name: serial-getty@ttyS0
  - enabled: yes
    name: sshd
  - enabled: yes
    name: wicked
  - enabled: yes
    name: wickedd-auto4
  - enabled: yes
    name: wickedd-dhcp4
  - enabled: yes
    name: wickedd-dhcp6
  - enabled: yes
    name: wickedd-nanny