---
- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: set /etc/hosts file
  template:
    src: ect_hosts.js
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: 0644


