---
- name: Resolve available hypervisor ISO
  ansible.builtin.uri:
    url: "http://bootserver/nexus/service/rest/v1/search/assets?q=hypervisor&repository=fawkes-images"
    method: GET
    return_content: true
  register: result

- name: Set iso_urn
  ansible.builtin.set_fact:
    iso_urn: "{{ result.content | from_json | json_query('items[*].path') | select('search', 'iso$') | list | first }}"

- name: Grub templates
  ansible.builtin.template:
    mode: '0644'
    src: grub.conf.j2
    dest: "{{ web_root }}/boot/grub.cfg"
    owner: dnsmasq
    group: tftp
