---
name: Ansible Lint
on: [push, pull_request]

jobs:
  lint:
    env:
      ANSIBLE_COLLECTIONS_PATH: './collections'
      ANSIBLE_LOG_PATH: './ansible.log' # Silence errors about unwritable `log_path`
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt

          # ansible-lint 6.17.2 and 6.18.0 have a bug that cause them to always run in offline mode, workaround it by installing collections by hand.
          ansible-galaxy collection install -vr requirements.yml

      - name: Ansible Lint
        run: |
          ansible-lint
